function d = getMicDistanceArray(dArray, s)
%GETMICDISTANCEARRAY Returns an array containg the vMic distances from the
%source

[dML, dMR] = getMicCartCoord(cm2M(dArray(1)));
    [dFL, dFR] = getMicCartCoord(dArray(2));
    dC = [0 cm2M(dArray(3))];
    d = [...
        getDistance(dML, s),...
        getDistance(dMR, s),...
        getDistance(dFL, s),...
        getDistance(dFR, s),...
        getDistance(dC, s)];
end

